# Server configuration
server:
  context-path: /micro
  port: 8083

# Spring properties
spring:
  application:
     name: orders-microservice

backend:
   host: backend-vbudiusibmcom.mybluemix.net
   port: 80
