apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders-lightblue-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: pod-orders
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: "registry.ng.bluemix.net/<namespace>/orders:latest"
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 60
          env:
          - name: "backend_host"
            value: "inventory-lightblue-service" 
          - name: "backend_port"
            value: "8085" 
---
apiVersion: v1
kind: Service
metadata:
  name: orders-lightblue-service
  labels:
    app: orders
spec:
  type: NodePort
  selector:
    app: orders
  ports:
   - protocol: TCP
     port: 8082
     nodePort: 30112
